<?php

/**
 * @file
 * Contains asu_brand.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * External XML file that provides a list of ASU Header Versions
 */
const ASU_BRAND_HEADER_VERSION_XML_URL = 'http://www.asu.edu/asuthemes/gtmheaders.xml';

/**
 * Header default version
 */
const ASU_BRAND_HEADER_VERSION_DEFAULT = '4.5';

/**
 * URL Basepath
 */
const ASU_BRAND_HEADER_BASEPATH_DEFAULT = 'http://www.asu.edu/asuthemes';

/**
 * Default template name
 */
const ASU_BRAND_HEADER_TEMPLATE_DEFAULT = 'default';

/**
 * Default Footer color
 */
const ASU_BRAND_FOOTER_COLOR_DEFAULT = '';

/**
 * Default cache lifetime is 48 Hours ( 60 x 60 x 48 )
 */
const ASU_BRAND_CACHE_LIFETIME = '172800';

/**
 * Default machine name of site menu to inject into the responsive header menu
 */
const ASU_BRAND_SITE_MENU_NAME_DEFAULT = 'main-menu';

/**
 * Implements hook_help().
 */
function asu_brand_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asu_brand module.
    case 'help.page.asu_brand':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides ASU header and footer blocks without the use of an ASU based theme.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function asu_brand_theme() {
  return [
    'asu_brand' => [
      'template' => 'asu_brand',
      'render element' => 'children',
    ],
  ];
}
